### ISSUE TITLE
Patch up melting recipes handling.

### ISSUE THREAD

**Issue by AnrDaemon** [alexbobp/TinkeredConstructer#1]
Would be wonderful, if melting recipes would directly allow OreDict entries, or at least windcard metadata.
Right now, if you specify wildcard meta, the recipe registered all right, but never match to anything.

**Comment by alexbobp** [comment]
Can you give me an example of what you _want_ the config to look like?

**Comment by AnrDaemon** [comment]
I don't want config to look like anything.
I want to tell the Smeltery to melt, say, minecraft:sand:\* and all sand should melt. Right now, it doesn't.
