### ISSUE TITLE
Village Tinkers trade oreberry bushes for half price

### ISSUE THREAD

**Issue by AnrDaemon** [alexbobp/TinkeredConstructer#2]
It may be a single occurence, but I noticed just now:
Villager offers a Tin oreberry bush for 12x Sticky Pistons plus Stencil Table.
I offer the asked price, pick the bush… Villager take pistons but not tables.

**Comment by alexbobp** [comment]
I am almost certain I didn't touch any code related to that... I would try to reproduce the issue on vanilla tinker's construct.  If you can't, and you can show me a repeatable test, I might be able to investigate.
